### ISSUE TITLE
[ BUG ] This extension no longer works.

### ISSUE THREAD

**Issue by MazeOfEncryption** [RootOperator/Youtube-row-fixer#14] opened 2021-11-18 20:12 UTC
As of recently, this extension no longer works as intended. 

Thumbnails are properly resized, but only 4 or 5 videos are being shown per row.
![image](https://user-images.githubusercontent.com/19843876/142489224-9dc5e029-59cd-4cb5-8b46-6bcffd9eb603.png)

**Comment by nbi1** [comment] 2021-11-18 20:18
I can confirm. Although I selected 6 the homepage only shows 5 and as soon as scrolling takes place it gets knocked down to 4.

**Comment by MazeOfEncryption** [comment] 2021-11-18 20:22
Interestingly, while the page is loading, the placeholder "thumbnails" _do_ seem to be working properly.
![image](https://user-images.githubusercontent.com/19843876/142490833-03d36c8b-a3b5-45df-b70f-874066a7161f.png)

**Comment by RootOperator** [comment] 2021-11-19 01:36
We are aware of this bug and are trying to figure out what changes YouTube made in order to try and fix this.

We are however very busy and therefor have very little time to figure out what is going on.
That said we will still try and use whatever time we have to figure out the issue.

**Comment by fearek** [comment] 2021-11-19 12:05
from my research I noticed that youtube does some calculations based on browser width to how many videos will be per row, the previous CSS change works until the script runs

**Comment by nbi1** [comment] 2021-11-20 05:03
Working now! The 11/18 update fixed it. Many thanks!

**Comment by RootOperator** [comment] 2021-11-24 07:56
I noticed the bug has reappeared so I'm reopening the issue

**Comment by nbi1** [comment] 2021-11-24 17:10
> I noticed the bug has reappeared so I'm reopening the issue

Just as you said that I tried it again and yes, it's back. It did work correctly for about 5 days though. Odd. It's as if YouTube is actively trying to defeat your enhancements. 😯

**Comment by scorpion421** [comment] 2021-11-25 23:20
Seems a bug from YouTube itself. I've done a Userstyle for myself months ago, because only 6 items per row on an ultrawide screen is just hilarious.

I nailed it down by myself, what's the cause is. And like I said: It seems like a bug for me.
Reason:
--ytd-grid-max-width seems to do nothing anymore. And this is where the magic belonged too, including

--ytd-rich-grid-items-per-row
--ytd-rich-grid-posts-per-row
--ytd-rich-grid-movies-per-row

All three can get modified without a problem and everything works - just not on "Home".

I share my userstyle with you - maybe you can grab something useful out of it. Take what you need :).

https://pastebin.com/L3FnAhPd

**Comment by RootOperator** [comment] 2021-11-26 04:42
> Seems to be a bug from YouTube itself. I've done a Userstyle for myself months ago, because only 6 items per row on an ultrawide screen is just hilarious.
> 
> I nailed it down by myself, what's the cause is. And like I said: It seems like a bug from YouTube itself for me.
> 
> Reason: --ytd-grid-max-width seems to do nothing anymore. And this is where the magic belonged too, including
> 
> --ytd-rich-grid-items-per-row --ytd-rich-grid-posts-per-row --ytd-rich-grid-movies-per-row
> 
> All three can get modified without a problem and everything works - just not on "Home".
> 
> I share my Userstyle with you - maybe you can grab something useful out of it. Take what you need :).
> 
> https://pastebin.com/L3FnAhPd

Thanks, we will definitely be looking through it and seeing if it can help us.

**Comment by scorpion421** [comment] 2021-11-28 03:13
And fixed in my userstyle :)

https://pastebin.com/mGpunyas

Again: Take what you need!

**Comment by RootOperator** [comment] 2021-11-29 06:38
We will be pushing a fix soon thanks to @scorpion421 with his custom userstyle, we are just testing some things at the moment but expect the fix to go live no later then today.

**Closed** 2021-11-29 06:56 UTC
Labels: bug
